// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzthcbbzuzvxqasidgrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dGhjYmJ6dXp2eHFhc2lkZ3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzMzMzQsImV4cCI6MjA2MTg0OTMzNH0.E3LqFKewcXuHPvHNhQYttAUY25TArrs2okVqKTPZGA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);